import Head from 'next/head';
import Homepage3 from '../components/Homepage3';

export default function Homepage3Page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/global.css" />
      </Head>
      <Homepage3 />  
    </>
  );
}