import Head from 'next/head';
import Payment from '../components/Payment';

export default function PaymentPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/global.css" />
      </Head>
      <Payment />  
    </>
  );
}