import Head from 'next/head';
import Profilepage4 from '../components/Profilepage4';

export default function Profilepage4Page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/global.css" />
      </Head>
      <Profilepage4 />  
    </>
  );
}