import Head from 'next/head';
import ProfilePage3 from '../components/ProfilePage3';

export default function ProfilePage3Page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/global.css" />
      </Head>
      <ProfilePage3 />  
    </>
  );
}