import Head from 'next/head';
import ProfilePage2 from '../components/ProfilePage2';

export default function ProfilePage2Page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/global.css" />
      </Head>
      <ProfilePage2 />  
    </>
  );
}