import Head from 'next/head';
import SlashScreen from '../components/SlashScreen';

export default function SlashScreenPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/global.css" />
      </Head>
      <SlashScreen />  
    </>
  );
}